### PR TITLE
Fixing _EnableA20 and _DisableA20 so that they properly return.

### PR DESCRIPTION
**Pull request by KyleJ61782**
Neither procedure has a return statement which means that executing them ends up falling through to a20_stop_if_active and a20_stop_if_inactive. This is a problem because both _EnableA20 and _DisableA20 are declared as far procedures, meaning all calls to them result in CS:IP being pushed onto the stack. However, falling through to those other procedures actually results only in near returns being performed, resulting in CS being left on the stack, which breaks passing the boot drive in DL during the chain load.

### CODE REVIEW

**Comment by AntAgna** [comment]
Thank you for finding an fixing this issue.

It seems you have changed the line endings on the file, which causes Git to think the whole file changed.
Would you mind amending the commit to preserve the line endings ?

**Comment by KyleJ61782** [comment]
My apologies! I inadvertently changed them. They should be fixed now.

**Comment by KyleJ61782** [comment]
I should add that falling through to a20_stop_if_active and a20_stop_if_inactive is likely unintended behavior to begin with as they're already called within _EnableA20 and _DisableA20, so this is fixing not only a bug but also properly representing intended behavior.

**Comment by AntAgna** [comment]
Thank you.
I have undone the whitespace changes to make it clear that there are only to changes in the file.

**Pull request merged**
